### ISSUE TITLE
Missing argument error

### ISSUE THREAD

**Issue by Goya-ye** [huggingface/parler-tts#151]
when i run the demo code ("Hey, how are you doing today?") offered, it has the error info"GenerationMixin._sample() missing 1 required positional argument: 'logits_warper'

**Comment by DerXter** [comment]
same issue here

**Comment by ylacombe** [comment]
You should be able to do it now, if you reinstall from the latest version

**Comment by DerXter** [comment]
Thank you for your support. From the last Transformers version (4.46.1), I'm getting this error:

`ValueError: 'dac' is already used by a Transformers config, pick another name.`

**Comment by ylacombe** [comment]
I don't get this on my side, could you double check that you reinstall parler following those instructions: https://github.com/huggingface/parler-tts?tab=readme-ov-file#installation ?

**Comment by medemi68** [comment]
Hey, I am getting this error as well:

Traceback (most recent call last):
```
  File "/parler-tts/parler_tts/__init__.py", line 8, in <module>
    from .modeling_parler_tts import (
  File "/parler-tts/parler_tts/modeling_parler_tts.py", line 64, in <module>
    AutoConfig.register("dac", DACConfig)
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/auto/configuration_auto.py", line 1070, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/auto/configuration_auto.py", line 769, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'dac' is already used by a Transformers config, pick another name.
```

**Comment by DerXter** [comment]
Hello @ylacombe, thank you very much for your support, it's working fine now. The sound quality is just amazing, kudos to you for the great work. @medemi68 Try uninstalling your ParlerTTS and reinstalling it as follows:

```
pip uninstall parler-tts
pip install --no-cache-dir --upgrade git+https://github.com/huggingface/parler-tts.git
```
