### ISSUE TITLE
Current version might be broken

### ISSUE THREAD

**Issue by medemi68** [huggingface/parler-tts#157]
Hey Team, 

I just spinned up an instance and noticed that the most recent commit to the master branch produces the following error:

Traceback (most recent call last):
  File "/parler-tts/stream-working.py", line 5, in <module>
    from parler_tts import ParlerTTSForConditionalGeneration, ParlerTTSStreamer
  File "/parler-tts/parler_tts/__init__.py", line 8, in <module>
    from .modeling_parler_tts import (
  File "/parler-tts/parler_tts/modeling_parler_tts.py", line 64, in <module>
    AutoConfig.register("dac", DACConfig)
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/auto/configuration_auto.py", line 1070, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/auto/configuration_auto.py", line 769, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'dac' is already used by a Transformers config, pick another name.

Any ideas? Should I try using an older branch/commit tag?

**Comment by medemi68** [comment]
For anyone who needs to use Parler right away and can't wait for a response, you can revert back to the previous commit using 
```
pip install git+https://github.com/huggingface/parler-tts.git@5d0aca9753ab74ded179732f5bd797f7a8c6f8ee
```
That is the previous commit.

**Comment by bocklucas** [comment]
> For anyone who needs to use Parler right away and can't wait for a response, you can revert back to the previous commit using 
> ```
> pip install git+https://github.com/huggingface/parler-tts.git@5d0aca9753ab74ded179732f5bd797f7a8c6f8ee
> ```
> That is the previous commit.

Can confirm it was broken for me as well and reverting fixed it, thanks @medemi68 !

**Comment by ylacombe** [comment]
Hey everyone, thanks for opening the issue and helping on identifying where it blocks.

It actually comes from the audio encoder. While I still have to figure out how to actually fix it while being backward compatible for person using it with the previous repo version, you can find fixed weights for the current version by using:
`model = ParlerTTSForConditionalGeneration.from_pretrained("parler-tts/parler-tts-large-v1", revision= "refs/pr/9")`

**Comment by bocklucas** [comment]
> Hey everyone, thanks for opening the issue and helping on identifying where it blocks.
> 
> It actually comes from the audio encoder. While I still have to figure out how to actually fix it while being backward compatible for person using it with the previous repo version, you can find fixed weights for the current version by using:
> `model = ParlerTTSForConditionalGeneration.from_pretrained("parler-tts/parler-tts-large-v1", revision= "refs/pr/9")`
> 
> 

Thanks @ylacombe 😊
