### ISSUE TITLE
Error when initializing model: AttributeError: can't set attribute 'frame_rate'

### ISSUE THREAD

**Issue by oliverkinch** [huggingface/parler-tts#164]
Running:

```sh
python helpers/model_init_scripts/init_model_600M.py ./parler-tts-untrained-600M --text_model "google/flan-t5-large" --audio_model "parler-tts/dac_44khZ_8kbps"
```

I get the following trace:

```sh
Traceback (most recent call last):
  File "/home/ubuntu/parler-tts/helpers/model_init_scripts/init_model_600M.py", line 21, in <module>
    encodec = AutoModel.from_pretrained(encodec_version)
  File "/home/ubuntu/parler-tts/.venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/ubuntu/parler-tts/.venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1041, in from_pretrained
    return config_class.from_dict(config_dict, **unused_kwargs)
  File "/home/ubuntu/parler-tts/.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 718, in from_dict
    config = cls(**config_dict)
  File "/home/ubuntu/parler-tts/.venv/lib/python3.10/site-packages/transformers/models/dac/configuration_dac.py", line 106, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/parler-tts/.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 318, in __init__
    raise err
  File "/home/ubuntu/parler-tts/.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 315, in __init__
    setattr(self, key, value)
  File "/home/ubuntu/parler-tts/.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 200, in __setattr__
    super().__setattr__(key, value)
AttributeError: can't set attribute 'frame_rate'
```

**Comment by oliverkinch** [comment]
In [DacConfig](https://github.com/huggingface/transformers/blob/main/src/transformers/models/dac/configuration_dac.py#L28) `frame_rate` is not an attribute, but a property. `frame_rate` should thus simply be removed from the [config](https://huggingface.co/parler-tts/dac_44khZ_8kbps/blob/main/config.json)?

**Comment by oliverkinch** [comment]
My hot fix was to ignore the `"frame_rate"` 

```python
        # Additional attributes without default values
        for key, value in kwargs.items():
            try:
                if key == "frame_rate":
                    continue
                setattr(self, key, value)
            except AttributeError as err:
                logger.error(f"Can't set {key} with value {value} for {self}")
                raise err
```

[The source code](https://github.com/huggingface/transformers/blob/893ad04fad145904ccb71e4e858e4134c32226b6/src/transformers/configuration_utils.py#L315)

**Comment by hongleng** [comment]
Same issue. This hotfix works.
