### ISSUE TITLE
run_parler_tts_training.py gives datasets.table.CastError error and failure

### ISSUE THREAD

**Issue by duringleaves** [huggingface/parler-tts#57]
I've run through the steps to train a single voice, and so far, so good.  But as soon as I get to the **Fine-tuning Parler-TTS** step, i'm hitting a wall.  It seems the previous Dataset Annotation instructions don't create all of the expected values?

`File "/Users/durin/AI/Projects/.parler-env/lib/python3.12/site-packages/datasets/table.py", line 2249, in cast_table_to_schema
    raise CastError(
datasets.table.CastError: Couldn't cast
text: string
utterance_pitch_mean: float
utterance_pitch_std: float
snr: double
c50: double
speaking_rate: string
phonemes: string
noise: string
reverberation: string
speech_monotony: string
-- schema metadata --
huggingface: '{"info": {"features": {"text": {"dtype": "string", "_type":' + 502
to
{'text': Value(dtype='string', id=None), 'utterance_pitch_mean': Value(dtype='float32', id=None), 'utterance_pitch_std': Value(dtype='float32', id=None), 'snr': Value(dtype='float64', id=None), 'c50': Value(dtype='float64', id=None), 'speaking_rate': Value(dtype='string', id=None), 'phonemes': Value(dtype='string', id=None), 'noise': Value(dtype='string', id=None), 'reverberation': Value(dtype='string', id=None), 'speech_monotony': Value(dtype='string', id=None), 'audio': Audio(sampling_rate=44100, mono=True, decode=True, id=None)}
because column names don't match
`

The script continues past the wandb connection, then fully fails with this error:
`Traceback (most recent call last):
  File "/Users/durin/AI/Projects/.parler-env/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/durin/AI/Projects/.parler-env/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/Users/durin/AI/Projects/.parler-env/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    simple_launcher(args)
  File "/Users/durin/AI/Projects/.parler-env/lib/python3.12/site-packages/accelerate/commands/launch.py", line 688, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/durin/AI/Projects/.parler-env/bin/python3', './training/run_parler_tts_training.py', '--model_name_or_path', 'parler-tts/parler_tts_mini_v0.1', '--feature_extractor_name', 'parler-tts/dac_44khZ_8kbps', '--description_tokenizer_name', 'parler-tts/parler_tts_mini_v0.1', '--prompt_tokenizer_name', 'parler-tts/parler_tts_mini_v0.1', '--report_to', 'wandb', '--overwrite_output_dir', 'true', '--train_dataset_name', 'diggum/vic01tts', '--train_metadata_dataset_name', 'diggum/vic01tts-tagged', '--train_dataset_config_name', 'default', '--train_split_name', 'train', '--eval_dataset_name', 'diggum/vic01tts', '--eval_metadata_dataset_name', 'diggum/vic01tts-tagged', '--eval_dataset_config_name', 'default', '--eval_split_name', 'train', '--max_eval_samples', '8', '--per_device_eval_batch_size', '8', '--target_audio_column_name', 'audio', '--description_column_name', 'text_description', '--prompt_column_name', 'text', '--max_duration_in_seconds', '20', '--min_duration_in_seconds', '2.0', '--max_text_length', '400', '--preprocessing_num_workers', '2', '--do_train', 'true', '--num_train_epochs', '2', '--gradient_accumulation_steps', '18', '--gradient_checkpointing', 'true', '--per_device_train_batch_size', '2', '--learning_rate', '0.00008', '--adam_beta1', '0.9', '--adam_beta2', '0.99', '--weight_decay', '0.01', '--lr_scheduler_type', 'constant_with_warmup', '--warmup_steps', '50', '--logging_steps', '2', '--freeze_text_encoder', 'true', '--audio_encoder_per_device_batch_size', '4', '--dtype', 'float32', '--seed', '456', '--output_dir', './output_dir_training/', '--temporary_save_to_disk', './audio_code_tmp/', '--save_to_disk', './tmp_dataset_audio/', '--dataloader_num_workers', '2', '--do_eval', '--predict_with_generate', '--include_inputs_for_metrics', '--group_by_length', 'true']' returned non-zero exit status 1.`

Just to confirm. when I run the previous step to view a sample from the dataset, here's the full contents:
`{'text': " Tonight at 11 on Utah's Talk Radio 105.9 KNRS.", 
  'utterance_pitch_mean': 114.15099334716797, 
  'utterance_pitch_std': 30.472904205322266, 
  'snr': 60.48295974731445, 
  'c50': 59.44480895996094, 
  'speaking_rate': 'quite slowly', 
  'phonemes': " tʌnaɪt æt  ɑn jutɔ'ɛs tɔk ɹeɪdioʊ . .", 
  'noise': 'slightly clear', 
  'reverberation': 'very confined sounding', 
  'speech_monotony': 'quite monotone', 
  'text_description': "'Very clear recording, but the speech is very monotone and slightly muffled by the recording.'"}`
  
  Not sure what I might be doing wrong, and I won't pretend to be an expert at this, so any guidance would be appreciated.

**Comment by ylacombe** [comment]
Hey @duringleaves, could you share the datasets you want to fine-tune the model on?
Are you using one single dataset or multiple ones ?
