### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by anioji** [huggingface/parler-tts#73]
I tried it on collab, I tried it on my hardware, and in both cases this error occurred during training.

```
gathered_tensor tensor([0], device='cuda:0')
06/15/2024 17:04:25 - INFO - __main__ - *** Encode target audio with encodec ***
 96%|██████████████████████████████████████████████████████████▌  | 24/25 [00:54<00:02,  2.27s/it]
Traceback (most recent call last):
  File "/home/lab/parler-tts/./training/run_parler_tts_training.py", line 1032, in <module>
    main()
  File "/home/lab/parler-tts/./training/run_parler_tts_training.py", line 437, in main
    lab = [l[:, : int(ratio * length)] for (l, ratio, length) in zip(lab, rat, lens)]
  File "/home/lab/parler-tts/venv/lib/python3.10/site-packages/torch/_tensor.py", line 1047, in __iter__
    raise TypeError("iteration over a 0-d tensor")
TypeError: iteration over a 0-d tensor
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/lab/parler-tts/wandb/offline-run-20240615_170319-y3l2zohb
wandb: Find logs at: ./wandb/offline-run-20240615_170319-y3l2zohb/logs
Traceback (most recent call last):
  File "/home/lab/parler-tts/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/lab/parler-tts/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/lab/parler-tts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/home/lab/parler-tts/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
    ```

**Comment by anioji** [comment]
Yesterday it was too late to try to do anything, so today I taked a couple of prints in this place. 

And judging from the segments that he allowed, then LEN is an array, and in the segment 24 this is a number ????

Audio dataset: Anioji/testra 
Metadata+Prompt: Anioji/test-rb-meta

```
 88%|██████████████████████████████████████████████████████████▉        | 22/25 [00:35<00:04,  1.39s/it]TYPES: <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>
VALUES: 
 LAB: tensor([[[568, 568, 568,  ..., 568, 568, 568],
         [778, 778, 804,  ..., 804, 804, 804],
         [338,  10,  10,  ...,  10,  10, 721],
         ...,
         [728, 741, 568,  ..., 568, 568, 623],
         [550, 378, 378,  ..., 378, 378, 795],
         [ 90, 731, 731,  ..., 731, 731, 731]],

        [[568, 568, 568,  ..., 568, 568, 568],
         [778, 778, 804,  ..., 804, 804, 804],
         [338,  10,  10,  ...,  10,  10, 721],
         ...,
         [728, 741, 568,  ..., 568, 568, 623],
         [550, 378, 378,  ..., 378, 378, 795],
         [ 90, 731, 731,  ..., 731, 731, 731]],

        [[568, 568, 568,  ..., 568, 568, 568],
         [778, 778, 804,  ..., 804, 804, 778],
         [338,  10,  10,  ...,  10,  10,  20],
         ...,
         [728, 741, 568,  ..., 568, 568, 728],
         [550, 378, 378,  ..., 378, 378, 507],
         [ 90, 731, 731,  ..., 731, 731, 158]],

        [[568, 568, 568,  ..., 568, 568, 568],
         [778, 778, 804,  ..., 804, 804, 804],
         [338,  10,  10,  ...,  10,  10, 721],
         ...,
         [728, 741, 568,  ..., 568, 568, 623],
         [550, 378, 378,  ..., 378, 378, 795],
         [ 90, 731, 731,  ..., 731, 731, 731]]], dtype=torch.int16), 
 RAT: tensor([0.0020, 0.0020, 0.0020, 0.0020]), 
LENS: tensor([393460, 424286, 617973, 437384])
 92%|█████████████████████████████████████████████████████████████▋     | 23/25 [00:37<00:02,  1.39s/it]TYPES: <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>
VALUES: 
 LAB: tensor([[[568, 568, 568,  ..., 568, 568, 568],
         [778, 778, 804,  ..., 804, 804, 778],
         [338,  10,  10,  ...,  10,  10, 921],
         ...,
         [728, 741, 568,  ..., 568, 568, 568],
         [550, 378, 378,  ..., 378, 378, 422],
         [ 90, 731, 731,  ..., 731, 731, 158]],

        [[568, 568, 568,  ..., 568, 568, 568],
         [778, 778, 804,  ..., 804, 804, 778],
         [338,  10,  10,  ...,  10,  10, 721],
         ...,
         [728, 741, 568,  ..., 568, 568, 313],
         [550, 378, 378,  ..., 378, 378, 746],
         [ 90, 731, 731,  ..., 731, 731, 731]],

        [[568, 568, 568,  ..., 568, 568, 568],
         [778, 778, 804,  ..., 804, 804, 778],
         [338,  10,  10,  ...,  10,  10, 921],
         ...,
         [728, 741, 568,  ..., 568, 568, 568],
         [550, 378, 378,  ..., 378, 378, 422],
         [ 90, 731, 731,  ..., 731, 731, 158]],

        [[568, 568, 568,  ..., 568, 568, 568],
         [778, 778, 804,  ..., 804, 804, 778],
         [338,  10,  10,  ...,  10,  10, 921],
         ...,
         [728, 741, 568,  ..., 568, 568, 568],
         [550, 378, 378,  ..., 378, 378, 422],
         [ 90, 731, 731,  ..., 731, 731, 158]]], dtype=torch.int16), 
 RAT: tensor([0.0020, 0.0020, 0.0020, 0.0020]), 
LENS: tensor([460096, 908195, 430989, 462212])
 96%|████████████████████████████████████████████████████████████████▎  | 24/25 [00:38<00:01,  1.49s/it]TYPES: <class 'torch.Tensor'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>
VALUES: 
 LAB: tensor([[[568, 568, 568,  ..., 568, 568, 530],
         [778, 778, 804,  ..., 804, 778, 778],
         [338,  10,  10,  ...,  10,  10, 921],
         ...,
         [728, 741, 568,  ..., 568, 568, 566],
         [550, 378, 378,  ..., 378, 378, 833],
         [ 90, 731, 731,  ..., 731, 731, 731]]], dtype=torch.int16), 
 RAT: 0.0019524467643350363, 
LENS: 541372
 96%|████████████████████████████████████████████████████████████████▎  | 24/25 [00:39<00:01,  1.64s/it]
Traceback (most recent call last):
  File "/home/lab/parler-tts/./training/run_parler_tts_training.py", line 1033, in <module>
    main()
  File "/home/lab/parler-tts/./training/run_parler_tts_training.py", line 438, in main
    lab = [l[:, : int(ratio * length)] for (l, ratio, length) in zip(lab, rat, lens)]
  File "/home/lab/parler-tts/venv/lib/python3.10/site-packages/torch/_tensor.py", line 1047, in __iter__
    raise TypeError("iteration over a 0-d tensor")
TypeError: iteration over a 0-d tensor


```

And command 

```

export FromDataset=Anioji/testra 
export FromDSMeta=Anioji/test-rb-meta

accelerate launch ./training/run_parler_tts_training.py \
    --model_name_or_path "parler-tts/parler_tts_mini_v0.1" \
    --feature_extractor_name "parler-tts/dac_44khZ_8kbps" \
    --description_tokenizer_name "parler-tts/parler_tts_mini_v0.1" \
    --prompt_tokenizer_name "parler-tts/parler_tts_mini_v0.1" \
    --overwrite_output_dir true \
    --train_dataset_name $FromDataset \
    --train_metadata_dataset_name $FromDSMeta \
    --train_dataset_config_name "default" \
    --train_split_name "train" \
    --eval_dataset_name $FromDataset \
    --eval_metadata_dataset_name $FromDSMeta \
    --eval_dataset_config_name "default" \
    --eval_split_name "train" \
    --max_eval_samples 8 \
    --per_device_eval_batch_size 8 \
    --target_audio_column_name "audio" \
    --description_column_name "text_description" \
    --prompt_column_name "text" \
    --max_duration_in_seconds 20 \
    --min_duration_in_seconds 2.0 \
    --max_text_length 400 \
    --preprocessing_num_workers 2 \
    --do_train true \
    --num_train_epochs 2 \
    --gradient_accumulation_steps 18 \
    --gradient_checkpointing true \
    --per_device_train_batch_size 2 \
    --learning_rate 0.00008 \
    --adam_beta1 0.9 \
    --adam_beta2 0.99 \
    --weight_decay 0.01 \
    --lr_scheduler_type "constant_with_warmup" \
    --warmup_steps 50 \
    --logging_steps 2 \
    --freeze_text_encoder true \
    --audio_encoder_per_device_batch_size 4 \
    --dtype "float16" \
    --seed 456 \
    --output_dir "./output_dir_training/" \
    --temporary_save_to_disk "./audio_code_tmp/" \
    --save_to_disk "./tmp_dataset_audio/" \
    --dataloader_num_workers 2 \
    --do_eval \
    --predict_with_generate \
    --include_inputs_for_metrics \
    --group_by_length true
    ```

**Comment by MingHui-Fang** [comment]
I've run into the same problem, and for me the reason for this error is that the last batch only has one audio sample.
This leads to a missing dimension in `lab, rat and lens`.
You can check the total amount of data and `audio_encoder_per_device_batch_size `. It might help to make sure that the last bach size is greater than 1.

https://github.com/huggingface/parler-tts/blob/8b8c576e2dbdc29172e30be7d68fac9357cd92c5/training/run_parler_tts_training.py#L428-L437

**Comment by anioji** [comment]
> I've run into the same problem, and for me the reason for this error is that the last batch only has one audio sample. This leads to a missing dimension in `lab, rat and lens`. You can check the total amount of data and `audio_encoder_per_device_batch_size `. It might help to make sure that the last bach size is greater than 1.
> 
> https://github.com/huggingface/parler-tts/blob/8b8c576e2dbdc29172e30be7d68fac9357cd92c5/training/run_parler_tts_training.py#L428-L437

By the way, this is possible, because I have 97, they were divided into 25, it turns out that one of the parts may actually be smaller than the others.п

Thank you for the thought.
I'll try to divide them into more even parts
I hope it should works

**Comment by MingHui-Fang** [comment]
I note that you have divided a total of 25 batch, with the first 24 batch size=4 and the last batch size=1. If you wish to verify quickly, you can simply set `audio_encoder_per_device_batch_size` to 5, which means that with 97 samples, the last batch size is greater than 1.

This might work.

**Comment by chunping-xt** [comment]
@MingHui-Fang I just got the same error, luckily I read this discussion and got over it. Is there any formula to not get this error again?

**Comment by MingHui-Fang** [comment]
> @MingHui-Fang I just got the same error, luckily I read this discussion and got over it. Is there any formula to not get this error again?

I'm glad my answer helped you with your problem. Maybe just make sure the batch size on each device is greater than 1, i.e. 
`total_data % audio_encoder_per_device_batch_size != 1`. 

Other way, you can add judgment conditions to this section 
https://github.com/huggingface/parler-tts/blob/8b8c576e2dbdc29172e30be7d68fac9357cd92c5/training/run_parler_tts_training.py#L433-L437 
to ensure that the variables `lab`, `rat`and `lens`are shaped properly.

**Comment by anioji** [comment]
I remake the set and it worked.

As a tip, keep in mind that the number of records is divisible by multiples of two without leaving a remainder.

I will close the Issue, but I think others will be able to open it if this question arises again. 

Thank you for help
